# Generated by Django 3.0.11 on 2020-12-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform', '0003_auto_20201204_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialists',
            name='task_num',
        ),
    ]
