# Generated by Django 3.0.11 on 2020-12-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform', '0010_tasks_id_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.IntegerField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['status_title'],
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_platform.Status', verbose_name='Статус'),
        ),
    ]
