# Generated by Django 3.0.11 on 2020-12-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform', '0011_auto_20201204_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_title',
            field=models.CharField(max_length=150, verbose_name='Статус'),
        ),
    ]
