# Generated by Django 3.0.11 on 2020-12-05 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_platform', '0012_auto_20201204_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_actions',
            name='files',
            field=models.FileField(blank=True, upload_to='log_files/%Y/%m/%d/', verbose_name='файл активности'),
        ),
        migrations.AlterField(
            model_name='log_actions',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_platform.Clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='log_actions',
            name='id_executor',
            field=models.CharField(blank=True, max_length=150, verbose_name='На кого назначена'),
        ),
        migrations.AlterField(
            model_name='log_actions',
            name='id_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_platform.Specialists', verbose_name='специалист'),
        ),
        migrations.AlterField(
            model_name='log_actions',
            name='id_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_platform.Tasks', verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='log_actions',
            name='images',
            field=models.ImageField(blank=True, upload_to='log_images/%Y/%m/%d/', verbose_name='Изображение активности'),
        ),
    ]
